# Generated by Django 2.0.4 on 2018-05-01 03:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import reporting.models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0004_auto_20180501_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(default=reporting.models.Event.get_default_category, on_delete=django.db.models.deletion.CASCADE, to='reporting.Category'),
        ),
    ]
