# Generated by Django 2.0.4 on 2018-05-01 10:38

import django.contrib.gis.db.models.fields
from django.contrib.gis.geos import fromstr
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0006_auto_20180501_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=fromstr("POINT(0 0)"), help_text='Location (longitude, latitude)', srid=4326),
            preserve_default=False,
        ),
    ]
