# Generated by Django 2.0.4 on 2018-05-01 12:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0007_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='author',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(help_text='POINT(latitude longitude)', srid=4326),
        ),
    ]
