# Generated by Django 2.0.4 on 2018-05-01 14:29

from django.db import migrations, models
import django.db.models.deletion
import reporting.models

def generate_default_event_states(apps, schema_editor):
    EventState = apps.get_model("reporting", "EventState")
    EventState.objects.all().get_or_create(name="to_validate")
    EventState.objects.all().get_or_create(name="valid")
    EventState.objects.all().get_or_create(name="solved")

class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0008_auto_20180501_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='reporting.EventState'),
        ),
        migrations.RunPython(generate_default_event_states),
    ]
